version : '3'

services:
    webserver:
        build: ./docker/php
        container_name: "api"
        ports:
            - "8080:80"
        networks:
            api-nosocomio-static-network:
                ipv4_address: 175.26.128.3
        volumes:
            - .:/var/www/html
            - "./docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini"
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        links:
            - db
        depends_on:
            - db
        command: bash -c "apache2-foreground"

    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        networks:
            api-nosocomio-static-network:
                ipv4_address: 175.26.128.4
        volumes:
          - db_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: nosocomio
          MYSQL_DATABASE: bd_nosocomio
          MYSQL_USER: root
          MYSQL_PASSWORD: root


networks:
   api-nosocomio-static-network:
        ipam:
            config:
                - subnet: 175.26.0.0/16

volumes:
    db_data:
