<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\View\Helper\Factory\LinkCdnFactory'      => __DIR__ . '/src/Application/View/Helper/Factory/LinkCdnFactory.php',
    'Application\View\Helper\Factory\LinkElementsFactory' => __DIR__ . '/src/Application/View/Helper/Factory/LinkElementsFactory.php',
    'Application\View\Helper\Link'                        => __DIR__ . '/src/Application/View/Helper/Link.php',
    'Application\Controller\IndexController'              => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Model\Collection\TestCollection'         => __DIR__ . '/src/Application/Model/Collection/TestCollection.php',
    'Application\Model\Table\UsuarioTable'                => __DIR__ . '/src/Application/Model/Table/UsuarioTable.php',
    'Application\Model\Table\TestTable'                   => __DIR__ . '/src/Application/Model/Table/TestTable.php',
    'Application\Model\Table\NosocomioTable'              => __DIR__ . '/src/Application/Model/Table/NosocomioTable.php',
    'Application\Module'                                  => __DIR__ . '/Module.php',
);
