<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Go Hospital ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->linkCdn('/img/favicon.ico')))
                ->prependStylesheet($this->linkCdn('/css/bootstrap.css'), "screen, print")
                ->prependStylesheet($this->linkCdn('/font-awesome/css/font-awesome.css'), "screen, print")
                ->prependStylesheet($this->linkCdn('/css/style.css'), "screen, print")
                ->prependStylesheet($this->linkCdn('/css/style-responsive.css'), "screen, print")
        ?>
        
    </head>
    <body>
        <section id="container" >
            <!--header start-->
            <header class="header black-bg">
                <div class="sidebar-toggle-box">
                    <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
                </div>
                <!--logo start-->
                <a href="/" class="logo"><b>Go Hospital</b></a>
                <!--logo end-->

                <div class="top-menu">
                    <ul class="nav pull-right top-menu">
                        <li><a class="logout" href="/logout">Cerrar Sesión</a></li>
                    </ul>
                </div>
            </header>
            <!--header end-->
            <!-- **********************************************************************************************************************************************************
            MAIN SIDEBAR MENU
            *********************************************************************************************************************************************************** -->
            <!--sidebar start-->
            <aside>
                <div id="sidebar"  class="nav-collapse ">
                    <!-- sidebar menu start-->
                    <ul class="sidebar-menu" id="nav-accordion">

                        <!--<p class="centered"><a href="/perfil"><img src="/img/ui-sam.jpg" class="img-circle" width="60"></a></p>-->
                        <h5 class="centered"><?php echo $this->user; ?></h5>

                        <li class="mt">
                            <a href="/dashboard">
                                <i class="fa fa-dashboard"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>

                        <li class="sub-menu">
                            <a href="/maps" >
                                <i class="fa fa-ambulance"></i>
                                <span>Hospital</span>
                            </a>
                        </li>

                        <li class="sub-menu">
                            <a href="/call" >
                                <i class="fa fa-phone"></i>
                                <span>SOS</span>
                            </a>
                        </li>

                    </ul>
                    <!-- sidebar menu end-->
                </div>
            </aside>
            <!--sidebar end-->
            <?php echo $this->content; ?>
            <!--footer start-->
            <footer class="site-footer">
                <div class="text-center">
                    2014 - Alvarez.is
                    <a href="blank.html#" class="go-top">
                        <i class="fa fa-angle-up"></i>
                    </a>
                </div>
            </footer>
            <!--footer end-->
        </section>
        <?php echo $this->inlineScript() ?>
        <!-- Scripts -->
        <?php
        $this->headScript()
                ->prependFile($this->linkCdn('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
                ->prependFile($this->linkCdn('https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
                ->prependFile($this->linkCdn('/js/common-scripts.js'))
                ->prependFile($this->linkCdn('/js/jquery.nicescroll.js'))
                ->prependFile($this->linkCdn('/js/jquery.scrollTo.min.js'))
                ->prependFile($this->linkCdn('/js/jquery.dcjqaccordion.2.7.js'), 'text/javascript', array('class' => 'include'))
                ->prependFile($this->linkCdn('/js/jquery.ui.touch-punch.min.js'))
                ->prependFile($this->linkCdn('/js/jquery-ui-1.9.2.custom.min.js'))
                ->prependFile($this->linkCdn('/js/bootstrap.min.js'))
                ->prependFile($this->linkCdn('/js/jquery.js'))
                ;
        echo $this->headScript();
        ?>
        <script>
            //custom select box

//            $(function () {
//                $('select.styled').customSelect();
//            });
        </script>
    </body>
</html>
