<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('Go Hospital ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/style-responsive.css'))
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/jquery.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-backstretch.min.js'))
        ;
        ?>

    </head>

    <body>
        <?php echo $this->content; ?>
        <script>
            $.backstretch("assets/img/login-bg.jpg", {speed: 500});
        </script>
    </body>
</html>