<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Api\Tests\Bootstrap'                                 => __DIR__ . '/tests/Bootstrap.php',
  'Application\Tests\Controller\SolrAbstractTest'       => __DIR__ . '/tests/Application/Model/SolrAbstractTest.php',
  'Application\Tests\Model\CookieElementsTest'          => __DIR__ . '/tests/Application/Model/Data/CookieElementsTest.php',
  'Application\Tests\Model\CookieTest'                  => __DIR__ . '/tests/Application/Model/Data/CookieTest.php',
  'Application\Tests\Model\Data\SolrTest'               => __DIR__ . '/tests/Application/Model/Data/SolrTest.php',
  'Application\Tests\ModuleTest'                        => __DIR__ . '/tests/Application/ModuleTest.php',
  'Api\Tests\BaseModuleTest'                            => __DIR__ . '/tests/Application/BaseModuleTest.php',
  'Application\Tests\Controller\BusquedaControllerTest' => __DIR__ . '/tests/Application/Controller/BusquedaControllerTest.php',
  'Api\Module'                                          => __DIR__ . '/Module.php',
  'Api\Controller\NosocomioRestController'               => __DIR__ . '/src/Api/Controller/NosocomioRestController.php',
);
