<!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

<div id="login-page">
    <div class="container">

        <form class="form-login" action="" method="post">
            <h2 class="form-login-heading">Iniciar sesión</h2>
            <div class="login-wrap">
                <input type="text" name="correo" class="form-control" placeholder="Correo" autofocus>
                <br>
                <input type="password" name="pass" class="form-control" placeholder="Contraseña">
                <label class="checkbox">
                    <span class="pull-right">
                        <!--<a data-toggle="modal" href="/#myModal"> Recuperar Contraseña?</a>-->
                    </span>
                </label>
                <button class="btn btn-theme btn-block" href="/" type="submit"><i class="fa fa-lock"></i> Iniciar sesión</button>
                <hr>

                <!--                <div class="login-social-link centered">
                                    <p>or you can sign in via your social network</p>
                                    <button class="btn btn-facebook" type="submit"><i class="fa fa-facebook"></i> Facebook</button>
                                    <button class="btn btn-twitter" type="submit"><i class="fa fa-twitter"></i> Twitter</button>
                                </div>-->
                <div class="registration">
                    ¿No tiene una cuenta? <br/>
                    <a class="" href="/registrarse">
                        Cree una.
                    </a>
                </div>

            </div>

            <!-- Modal -->
<!--            <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Forgot Password ?</h4>
                        </div>
                        <div class="modal-body">
                            <p>Enter your e-mail address below to reset your password.</p>
                            <input type="text" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix">

                        </div>
                        <div class="modal-footer">
                            <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
                            <button class="btn btn-theme" type="button">Submit</button>
                        </div>
                    </div>
                </div>
            </div>-->
            <!-- modal -->
        </form>	  	

    </div>
</div>