<!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

<div id="login-page">
    <div class="container">

        <form class="form-login" action="">
            <h2 class="form-login-heading">Registrarse</h2>
            <div class="login-wrap">
                <input type="text" class="form-control" placeholder="Correo" autofocus>
                <br>
                <input type="password" class="form-control" placeholder="Contraseña">
                <br>
                <input type="repassword" class="form-control" placeholder="Confirmar Contraseña">
                <label class="checkbox">
                    <span class="pull-right">
                        <!--<a data-toggle="modal" href="/#myModal"> Recuperar Contraseña?</a>-->
                    </span>
                </label>
                <button class="btn btn-theme btn-block" href="/" type="submit"><i class="fa fa-lock"></i> Registrarse</button>
                <hr>
                <div class="registration">
                    <a class="" href="/">
                        Iniciar sesión.
                    </a>
                </div>

            </div>
        </form>	  	

    </div>
</div>